# åšå®¢å…³é”®è¯
keywords: hexo, HTML, CSS, Javascript, Node.js

# ä½œè€…ä¿¡æ¯
author: Cara,zzxxcclloopp@gmail.com

# åšå®¢æè¿°
description: å’¸é±¼çš„åšå®¢å’Œå­¦ä¹ ç¬”è®°ğŸ“’ 'Lok-Tar Ogar!'.

# å³ä¸Šè§’å¤´åƒ
avatar: http://ordjgqxuv.bkt.clouddn.com/cara_30/WechatIMG8.jpeg

# è¯„è®ºæ¡†
gentie:

# githubè´¦å·
github: Caraws
